version: "3"
services:
    react-app:
        container_name: react_container
        build:
            context: ./music-app
            dockerfile: react-app
        ports:
            - 3000:3000
        volumes:
            - ".:/app"
            - "/app/node_modules"
        environment:
             - NODE_ENV=development
        stdin_open: true
    serverproxy:
        build: 
            context: ./serverProxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./serverProxy/default.conf:/etc/nginx/conf.d/default.conf:ro
           # - ./serverProxy/certs:/etc/nginx/certs
    loginserver:
        container_name: nodeLogin
        build:
            context: ./loginDataServer
            dockerfile: loginDataServer
        environment:
            - NODE_ENV=development
    musicserver:
        container_name: nodeMusic
        build:
            context: ./musicServer
            dockerfile: musicServer
        environment:
            - NODE_ENV=development
